[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.filesystem = littlefs
board_build.partitions = huge_app.csv

lib_deps =
  ; No external libs needed — all are part of the ESP32 Arduino core
